### ISSUE TITLE
JavaScript Error in the main process

### ISSUE THREAD

**Issue by drewtwitchell** [Alamantus/GooglePhotosExportOrganizer#11]
Hello, using the latest 1.1.1 and getting the following error.

`Uncaught Exception:
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
at onwrite (_stream_writable.js:437:11)
at ProxyWriter.emit (events.js:315:20)
at FileWriter.emit (events.js:315:20)
at end (/private/var/folders/rs/51g4s6_j0wg7n96zpz4ps6b80000gp/T/AppTranslocation/238AEED8-7D31-41A5-8D20-1F618AE42910/d/Google Photos Export Organizer.app/Contents/Resources/app.asar/node_modules/fstream/lib/writer.js:324:14)
at /private/var/folders/rs/51g4s6_j0wg7n96zpz4ps6b80000gp/T/AppTranslocation/238AEED8-7D31-41A5-8D20-1F618AE42910/d/Google Photos Export Organizer.app/Contents/Resources/app.asar/node_modules/fstream/lib/writer.js:314:34
at endUtimes (/private/var/folders/rs/51g4s6_j0wg7n96zpz4ps6b80000gp/T/AppTranslocation/238AEED8-7D31-41A5-8D20-1F618AE42910/d/Google Photos Export Organizer.app/Contents/Resources/app.asar/node_modules/fstream/lib/writer.js:238:46)
at setProps (/private/var/folders/rs/51g4s6_j0wg7n96zpz4ps6b80000gp/T/AppTranslocation/238AEED8-7D31-41A5-8D20-1F618AE42910/d/Google Photos Export Organizer.app/Contents/Resources/app.asar/node_modules/fstream/lib/writer.js:297:5)
at /private/var/folders/rs/51g4s6_j0wg7n96zpz4ps6b80000gp/T/AppTranslocation/238AEED8-7D31-41A5-8D20-1F618AE42910/d/Google Photos Export Organizer.app/Contents/Resources/app.asar/node_modules/fstream/lib/writer.js:287:7
at callback (/private/var/folders/rs/51g4s6_j0wg7n96zpz4ps6b80000gp/T/AppTranslocation/238AEED8-7D31-41A5-8D20-1F618AE42910/d/Google Photos Export Organizer.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:295:20)
at FSReqCallback.oncomplete (fs.js:173:5)`

**Comment by valentinlietz** [comment]
Happens to me too

**Comment by Alamantus** [comment]
@drewtwitchell @valentinlietz Hi there, when specifically does this error occur? What process is being run? Or does this just happen when the app is loaded?

Also, what operating system are you using?

**Comment by drewtwitchell** [comment]
@Alamantus this happens when you choose to extract the takeout directory or directories. The app opens no problem, but when it starts to chew through the extracting it runs into that error and nothing completes and the status bar goes to full and adds an exclamation point at the end. the only way to get out of the extraction task is to either kill the app or hit the back button to start over, but it does the same thing again. NOTE - this error presents itself as a popup that you have to hit ok to about 4-5 times for it to go away.

**Comment by drewtwitchell** [comment]
I am also running latest Big Sur macOS on the new M1 ARM mac chipset.
